name: inclass15
description: A fully featured, animated Firebase Inventory Manager app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core & Firestore
  firebase_core: ^2.24.0
  cloud_firestore: ^4.9.5

  # State management
  provider: ^6.1.2

  # Animations
  flutter_animate: ^4.5.0

  # For charts in dashboard
  fl_chart: ^0.68.0

  # For search and UI icons
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
